### ISSUE TITLE
Done with Yelp

### ISSUE THREAD

**Issue by muinmomin** [muinmomin/Yelp-CodePath#1]
My app is complete, please review. /cc @codepathreview

**Comment by minhchau273** [comment]
:+1: Nice work! This primary challenge of this homework was to learn how to use AutoLayout to build adaptive UI's that work across many different screen sizes and orientations. If you haven't already, we recommend going back and running your homework again while rotating the device / simulator to ensure your AutoLayout constraints function as expected.

### Some small comments:
- Nice work specifying the Auto Layout constraints.
- It's not a big deal but in case there is no result, you should show a label `No results found` to make your app more friendly :wink:
- You miss the trailing space to super view constraint so that the `categoriesLabel` is truncated in this cell.

<img width="318" alt="screen shot 2016-02-14 at 4 54 48 pm" src="https://cloud.githubusercontent.com/assets/12395213/13033064/e81f14ac-d33b-11e5-8d26-06eae983be7b.png">
- Great job implementing map view the detail page :star2: 

We have a detailed [Project 3 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_3_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
